import Head from "next/head";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";
import { useState } from "react";
import SearchCom from "@/components/SearchCom";

export default function Search() {
  const API_KEY = process.env.API_KEY;
  console.log(API_KEY);

  const [search, setSearch] = useState("");
  const [results, setResults] = useState([]);

  function getSearchdata(event) {
    event.preventDefault();
    try {
      fetch(
        `https://api.themoviedb.org/3/search/movie?api_key=${API_KEY}&query=${search}`
      )
        .then((res) => res.json())
        .then((data) => setResults(data.results));
    } catch (e) {}
  }

  function handleChange(event) {
    setSearch(event.target.value);
  }

  return (
    <>
      <Head>
        <title>Hulu-Movie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Navbar />
        <form type="onSubmit">
          <div className="  ml-8  mr-8 mt-8 gap-2 relative max-w-sm  border-yellow-400 sm:ml-20 ">
            <input
              className=" text-lg p-3 w-full text-black rounded-xl"
              id="inputTxt"
              placeholder="Search"
              value={search}
              onChange={handleChange}
            ></input>
            <button
              className=" absolute right-0 text-lg p-2 mt-1 rounded-full bg-bubble-gum mr-1"
              onClick={getSearchdata}
            >
              Go
            </button>
          </div>
        </form>

        {results ? (
          <SearchCom results={results} />
        ) : (
          <div className="  ml-8 mt-5 text-2xl sm:ml-20 ">
            No Result for your search
          </div>
        )}
      </main>
    </>
  );
}
